### ISSUE TITLE
拉取镜像报错

### ISSUE THREAD

**Issue by Dyinglight5** [ctfhub-team/base_image#1]
=> ERROR [internal] load metadata for docker.io/ctfhub_base/web_nginx_mysql_php_5.6:latest   
 > [internal] load metadata for docker.io/ctfhub_base/web_nginx_mysql_php_5.6:latest:
------
Dockerfile:1
--------------------
   1 | >>> FROM ctfhub_base/web_nginx_mysql_php_5.6
   2 |     
   3 |     COPY files/flag.sh /flag.sh
--------------------
ERROR: failed to solve: ctfhub_base/web_nginx_mysql_php_5.6: failed to resolve source metadata for docker.io/ctfhub_base/web_nginx_mysql_php_5.6:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
无权限？

**Comment by yw9381** [comment]
在dockerhub上的namespace应当是ctfhub，而不是ctfhub_base，在readme里有说明这个问题了
